platform :ios, '10.0' 
use_frameworks!

def shared_pods
  pod 'SaltedgeAuthenticatorSDK', :path => '../'
  pod 'ReachabilitySwift'
  pod 'TinyConstraints'
  pod 'SDWebImage', '5.1.0'
  pod 'RealmSwift', '5.4.7', :inhibit_warnings => true
  pod 'Realm', '5.4.7', :inhibit_warnings => true
  pod 'Valet', '~> 3.2.8'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
end

target 'Authenticator_Example' do
  shared_pods
end

target 'Authenticator_Tests' do
    pod 'Quick'
    pod 'Nimble'
    shared_pods
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
	config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      end
    end
end
